new change

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Check if this is the initial commit
-echo "pre commit fails"
-exit 1
+#echo "pre commit fails"
+#exit 1
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
 echo "pre-commit: About to create a new commit..."
